import React from 'react';

// import { Container } from './styles';

const UseTerms: React.FC = () => {
  return (
    <div><div class="row"><div class="col-12"><div><h1><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Termos e Condições</font></font></h1>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Última atualização: 14 de julho de 2021</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Por favor, leia estes termos e condições cuidadosamente antes de usar nosso serviço.</font></font></p>
<h1><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Interpretação e Definições</font></font></h1>
<h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Interpretação</font></font></h2>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">As palavras cuja letra inicial é maiúscula têm significados definidos nas seguintes condições. </font><font style="vertical-align: inherit;">As seguintes definições devem ter o mesmo significado, independentemente de aparecerem no singular ou no plural.</font></font></p>
<h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Definições</font></font></h2>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Para os fins destes Termos e Condições:</font></font></p>
<ul>
<li>
<p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Afiliada</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> significa uma entidade que controla, é controlada ou está sob o controle comum de uma parte, onde "controle" significa propriedade de 50% ou mais das ações, participação acionária ou outros títulos com direito a voto para eleição de diretores ou outra autoridade administrativa .</font></font></p>
</li>
<li>
<p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">País</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> se refere a: Brasil</font></font></p>
</li>
<li>
<p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Empresa</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> (referida como "a Empresa", "Nós", "Nós" ou "Nosso" neste Acordo) refere-se ao Chat pi.</font></font></p>
</li>
<li>
<p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Dispositivo</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> significa qualquer dispositivo que pode acessar o Serviço, como um computador, um telefone celular ou um tablet digital.</font></font></p>
</li>
<li>
<p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Serviço</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> refere-se ao site.</font></font></p>
</li>
<li>
<p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Termos e Condições</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> (também chamados de "Termos") significam estes Termos e Condições que constituem o acordo completo entre Você e a Empresa em relação ao uso do Serviço. </font><font style="vertical-align: inherit;">Este acordo de Termos e Condições foi criado com a ajuda do </font></font><a href="https://www.termsfeed.com/terms-conditions-generator/" target="_blank"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Gerador de Termos e Condições</font></font></a><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> .</font></font></p>
</li>
<li>
<p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Serviço de mídia social de terceiros</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> significa qualquer serviço ou conteúdo (incluindo dados, informações, produtos ou serviços) fornecido por um terceiro que pode ser exibido, incluído ou disponibilizado pelo Serviço.</font></font></p>
</li>
<li>
<p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">O site</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> refere-se ao Chat pi, acessível em </font></font><a href="https://chatpi.vercel.app/" rel="external nofollow noopener" target="_blank"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">https://chatpi.vercel.app/</font></font></a></p>
</li>
<li>
<p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Você</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> significa o indivíduo que acessa ou usa o Serviço, ou a empresa ou outra pessoa jurídica em nome da qual tal indivíduo está acessando ou usando o Serviço, conforme aplicável.</font></font></p>
</li>
</ul>
<h1><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Reconhecimento</font></font></h1>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Estes são os Termos e Condições que regem o uso deste Serviço e o acordo que opera entre Você e a Empresa. </font><font style="vertical-align: inherit;">Estes Termos e Condições estabelecem os direitos e obrigações de todos os usuários em relação ao uso do Serviço.</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Seu acesso e uso do Serviço estão condicionados à Sua aceitação e cumprimento destes Termos e Condições. </font><font style="vertical-align: inherit;">Estes Termos e Condições se aplicam a todos os visitantes, usuários e outras pessoas que acessam ou usam o Serviço.</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Ao acessar ou usar o Serviço, você concorda em obedecer a estes Termos e Condições. </font><font style="vertical-align: inherit;">Se você discordar de qualquer parte destes Termos e Condições, você não poderá acessar o Serviço.</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Você declara que tem mais de 18 anos. A Empresa não permite que menores de 18 anos usem o Serviço.</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Seu acesso e uso do Serviço também estão condicionados à sua aceitação e conformidade com a Política de Privacidade da Empresa. </font><font style="vertical-align: inherit;">Nossa Política de Privacidade descreve nossas políticas e procedimentos sobre a coleta, uso e divulgação de Suas informações pessoais quando Você usa o Aplicativo ou o Site e informa sobre Seus direitos de privacidade e como a lei o protege. </font><font style="vertical-align: inherit;">Por favor, leia nossa Política de Privacidade cuidadosamente antes de usar nosso serviço.</font></font></p>
<h1><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Links para outros sites</font></font></h1>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Nosso serviço pode conter links para sites ou serviços de terceiros que não são de propriedade ou controlados pela empresa.</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">A Empresa não tem controle e não assume responsabilidade pelo conteúdo, políticas de privacidade ou práticas de quaisquer sites ou serviços de terceiros. </font><font style="vertical-align: inherit;">Você também reconhece e concorda que a Empresa não será responsável ou responsabilizada, direta ou indiretamente, por qualquer dano ou perda causado ou alegadamente causado por ou em conexão com o uso ou confiança em qualquer conteúdo, bens ou serviços disponíveis em ou por meio de qualquer um desses sites ou serviços.</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Aconselhamos vivamente que leia os termos e condições e políticas de privacidade de quaisquer sites ou serviços de terceiros que visite.</font></font></p>
<h1><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Terminação</font></font></h1>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Podemos encerrar ou suspender Seu acesso imediatamente, sem aviso prévio ou responsabilidade, por qualquer motivo, incluindo, sem limitação, se você violar estes Termos e Condições.</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Após a rescisão, Seu direito de usar o Serviço cessará imediatamente.</font></font></p>
<h1><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Limitação de responsabilidade</font></font></h1>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Não obstante quaisquer danos em que Você possa incorrer, toda a responsabilidade da Empresa e de qualquer um de seus fornecedores sob qualquer disposição destes Termos e Seu recurso exclusivo para todos os anteriores serão limitados ao valor realmente pago por Você por meio do Serviço ou 100 USD se Você não comprou nada por meio do Serviço.</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Até a extensão máxima permitida pela lei aplicável, em nenhum caso a Empresa ou seus fornecedores serão responsáveis &ZeroWidthSpace;&ZeroWidthSpace;por quaisquer danos especiais, incidentais, indiretos ou consequentes de qualquer natureza (incluindo, mas não se limitando a, danos por perda de lucros, perda de dados ou outras informações, para interrupção de negócios, por danos pessoais, perda de privacidade decorrente de ou de alguma forma relacionada ao uso ou incapacidade de usar o Serviço, software de terceiros e / ou hardware de terceiros usado com o Serviço, ou caso contrário, em conexão com qualquer disposição destes Termos), mesmo se a Empresa ou qualquer fornecedor tiver sido avisado da possibilidade de tais danos e mesmo se a solução falhar em seu propósito essencial.</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Alguns estados não permitem a exclusão de garantias implícitas ou limitação de responsabilidade por danos incidentais ou conseqüenciais, o que significa que algumas das limitações acima podem não se aplicar. </font><font style="vertical-align: inherit;">Nesses estados, a responsabilidade de cada parte será limitada ao máximo permitido por lei.</font></font></p>
<h1><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Isenção de responsabilidade "COMO ESTÁ" e "CONFORME DISPONÍVEL"</font></font></h1>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">O Serviço é fornecido a Você "COMO ESTÁ" e "COMO DISPONÍVEL" e com todas as falhas e defeitos sem garantia de qualquer tipo. </font><font style="vertical-align: inherit;">Até a extensão máxima permitida pela lei aplicável, a Empresa, em seu próprio nome e em nome de suas Afiliadas e seus respectivos licenciantes e prestadores de serviços, renuncia expressamente a todas as garantias, sejam expressas, implícitas, estatutárias ou de outra forma, com relação ao Serviço, incluindo todas as garantias implícitas de comercialização, adequação a um propósito específico, título e não violação, e garantias que podem surgir durante a negociação, desempenho, uso ou prática comercial. </font><font style="vertical-align: inherit;">Sem limitação ao acima exposto, a Empresa não oferece nenhuma garantia ou compromisso, e não faz qualquer representação de qualquer tipo de que o Serviço atenderá aos seus requisitos, alcançará os resultados pretendidos,</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Sem limitar o precedente, nem a Empresa nem qualquer fornecedor da empresa faz qualquer representação ou garantia de qualquer tipo, expressa ou implícita: (i) quanto à operação ou disponibilidade do Serviço, ou as informações, conteúdo e materiais ou produtos incluído nele; </font><font style="vertical-align: inherit;">(ii) que o Serviço será ininterrupto ou livre de erros; </font><font style="vertical-align: inherit;">(iii) quanto à precisão, confiabilidade ou atualidade de qualquer informação ou conteúdo fornecido por meio do Serviço; </font><font style="vertical-align: inherit;">ou (iv) que o Serviço, seus servidores, o conteúdo ou e-mails enviados de ou em nome da Empresa estão livres de vírus, scripts, cavalos de tróia, worms, malware, bombas de tempo ou outros componentes prejudiciais.</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Algumas jurisdições não permitem a exclusão de certos tipos de garantias ou limitações sobre os direitos legais aplicáveis &ZeroWidthSpace;&ZeroWidthSpace;de um consumidor, portanto, algumas ou todas as exclusões e limitações acima podem não se aplicar a você. </font><font style="vertical-align: inherit;">Mas, em tal caso, as exclusões e limitações estabelecidas nesta seção serão aplicadas na maior medida exequível de acordo com a lei aplicável.</font></font></p>
<h1><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Lei Aplicável</font></font></h1>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">As leis do país, excluindo seus conflitos de normas legais, regerão estes Termos e o uso do Serviço por você. </font><font style="vertical-align: inherit;">O uso do Aplicativo também pode estar sujeito a outras leis locais, estaduais, nacionais ou internacionais.</font></font></p>
<h1><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Resolução de disputas</font></font></h1>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Se você tiver qualquer dúvida ou dúvida sobre o Serviço, concorda em primeiro tentar resolver a disputa informalmente, entrando em contato com a Empresa.</font></font></p>
<h1><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Para usuários da União Europeia (UE)</font></font></h1>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Se for um consumidor da União Europeia, beneficiará de quaisquer disposições obrigatórias da lei do país em que reside.</font></font></p>
<h1><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Conformidade Legal dos Estados Unidos</font></font></h1>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Você declara e garante que (i) Você não está localizado em um país que está sujeito ao embargo do governo dos Estados Unidos, ou que foi designado pelo governo dos Estados Unidos como um país de "apoio ao terrorismo" e (ii) Você não está listado em qualquer lista do governo dos Estados Unidos de partes proibidas ou restritas.</font></font></p>
<h1><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Divisibilidade e renúncia</font></font></h1>
<h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Separabilidade</font></font></h2>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Se qualquer disposição destes Termos for considerada inexequível ou inválida, tal disposição será alterada e interpretada para cumprir os objetivos de tal disposição na maior medida possível sob a lei aplicável e as disposições restantes continuarão em pleno vigor e efeito.</font></font></p>
<h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Renúncia</font></font></h2>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Exceto conforme disposto neste documento, a falha em exercer um direito ou exigir o cumprimento de uma obrigação sob estes Termos não afetará a capacidade de uma parte de exercer tal direito ou exigir tal cumprimento em qualquer momento posterior, nem deverá ser a renúncia de uma violação constituirá uma renúncia de qualquer violação subsequente.</font></font></p>
<h1><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Tradução de interpretação</font></font></h1>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Estes Termos e Condições podem ter sido traduzidos se os tivermos disponibilizado para você em nosso serviço. </font><font style="vertical-align: inherit;">Você concorda que o texto original em inglês prevalecerá em caso de disputa.</font></font></p>
<h1><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Mudanças nestes Termos e Condições</font></font></h1>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Nós nos reservamos o direito, a nosso exclusivo critério, de modificar ou substituir estes Termos a qualquer momento. </font><font style="vertical-align: inherit;">Se uma revisão for material, Faremos todos os esforços razoáveis &ZeroWidthSpace;&ZeroWidthSpace;para fornecer um aviso com pelo menos 30 dias de antecedência à entrada em vigor de quaisquer novos termos. </font><font style="vertical-align: inherit;">O que constitui uma alteração material será determinado a nosso exclusivo critério.</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Ao continuar a acessar ou usar nosso serviço após essas revisões entrarem em vigor, você concorda em obedecer aos termos revisados. </font><font style="vertical-align: inherit;">Se você não concordar com os novos termos, no todo ou em parte, pare de usar o site e o Serviço.</font></font></p>
<h1><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Contate-Nos</font></font></h1>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Se você tiver alguma dúvida sobre estes Termos e Condições, pode entrar em contato conosco:</font></font></p>
<ul>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Por email: natanaelima@mundotech.dev</font></font></li>
</ul></div></div></div></div>
  );
}

export default UseTerms;
